In [13]:
import numpy as np
from utils import *
from model import *
from model_functions import *
import h5py

In [14]:
train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes = cat_data_loader()
x_train, y_train, x_test, y_test, classes = flatten_data(train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes)

print(x_train.shape)
print(y_train.shape)

print(x_test.shape)
print(y_test.shape)




(12288, 209)
(1, 209)
(12288, 50)
(1, 50)


In [15]:
layers = [x_train.shape[0], 8, 1]
#after_train_parameters = train_model(x_train,y_train, layers=layers ,learning_rate=0.005,train_iterations=1500,cost_function=max_entropy_cost)
def net_init(layers):

    layers_parameters = {}
    L = len(layers)

    for layer_num in range(1, L):
        layers_parameters['weights_matrix ' + str(layer_num)] = np.random.rand(layers[layer_num], layers[layer_num-1])*0.01
        layers_parameters['bias_v ' + str(layer_num)] = np.zeros((layers[layer_num], 1))

    return layers_parameters

parameters = net_init(layers)


In [16]:
def forward_propagate(activation_prev, weights_matrix, bias_v, function):
    """Calculate linear output"""
    
    linear_output = np.dot(weights_matrix, activation_prev) + bias_v


    print(activation_prev, weights_matrix.tolist(), bias_v.tolist())
    print("linear_output",linear_output.tolist())
    print(linear_output.shape)


    """Choose activation"""
    if function == "sigmoid":
        activation_output, activation_cache = sigmoid(linear_output)
    elif function == "relu":
        activation_output, activation_cache = relu(linear_output)

    linear_cache = activation_prev, weights_matrix, bias_v


    return activation_output, linear_cache, activation_cache




def L_forward_propagate(X, parameters, layers):
    L = len(parameters)//2
    activation_prev = X
    caches = []


    for layer in range(1, L):
        weights_matrix = parameters['weights_matrix ' + str(layer)]
        bias_v = parameters['bias_v ' + str(layer)]
        
        
        activation_output, linear_cache, activation_cache = forward_propagate(activation_prev, weights_matrix, bias_v, "relu")
        caches.append((activation_output, linear_cache, activation_cache))
        activation_prev = activation_output

    """Propagate to L(final) layer, with different activation function"""
    weights_matrix = parameters['weights_matrix ' + str(L)]
    bias_v = parameters['bias_v ' + str(L)]
    activation_output, linear_cache, activation_cache = forward_propagate(activation_prev, weights_matrix, bias_v, "sigmoid")
    caches.append((activation_output, linear_cache, activation_cache))

    y_predict = activation_output
    
    return y_predict, caches






y_predict, caches = L_forward_propagate(x_train, parameters, layers)

print(y_predict)
assert(y_predict.shape == (1, 209))

[[0.06666667 0.12156863 0.21960784 ... 0.26666667 0.12941176 0.16078431]
 [0.27843137 0.13333333 0.17254902 ... 0.18431373 0.30196078 0.15686275]
 [0.19215686 0.30980392 0.15686275 ... 0.14901961 0.18039216 0.29411765]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]] [[0.00985380645890492, 0.0007539047154595191, 0.0004286670759645195, 0.008424318731591326, 0.004338921632498951, 0.00568177692814904, 0.0026703339247660406, 0.004671572937269632, 0.0009465926683812976, 0.006258152318951119, 0.00886592751655006, 0.005219125884337312, 0.009403065591835598, 0.004885244141440826, 0.0020183046092325106, 0.007214156072243575, 0.009759605431922353, 0.008929501126306496, 0.0072549178667912695, 0.00014624606821633912, 0.008267793156291748, 0.005583688528034172, 0.003776821066758338, 0.008384189576074359, 0.0005142865320476164